vich_uploader:
  db_driver: orm
  storage: flysystem

  mappings:
    document_file:
      uri_prefix: '%env(R2_PUBLIC_URL)%'
      upload_destination: documents.storage
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
